refind

diff --git a/usr/local/bin/arcolinux-nvidia-drm-wayland b/usr/local/bin/arcolinux-nvidia-drm-wayland
--- a/usr/local/bin/arcolinux-nvidia-drm-wayland
+++ b/usr/local/bin/arcolinux-nvidia-drm-wayland
@@ -41,16 +41,32 @@ if [ -f /usr/share/wayland-sessions/hyprland.desktop ] || [ -f /usr/share/waylan
 		fi
 
 		# REFIND
-		if [ -f /boot/refind_linux.conf ]; then
+		# Path to the refind_linux.conf file
+		CONF_FILE="/boot/refind_linux.conf"
+
+		# Check if the refind_linux.conf file exists
+		if [ -f "$CONF_FILE" ]; then
 		    # Check if 'nvidia-drm.modeset=1' is already in the kernel options
-		    if ! grep -q "nvidia-drm.modeset=1" /boot/refind_linux.conf; then
-		        # Use sed to append 'nvidia-drm.modeset=1' to the kernel options
-		        sudo sed -i "s/\" rw /\" rw nvidia-drm.modeset=1 /" /boot/refind_linux.conf
-		        echo "Added 'nvidia-drm.modeset=1' to the kernel options in /boot/refind_linux.conf"
+		    if grep -q "nvidia-drm.modeset=1" "$CONF_FILE"; then
+		        echo "'nvidia-drm.modeset=1' is already present in $CONF_FILE."
 		    else
-		        echo "'nvidia-drm.modeset=1' is already present in /boot/refind_linux.conf"
+		        # Backup the original configuration file
+		        sudo cp "$CONF_FILE" "${CONF_FILE}.bak"
+
+		        # Attempt to add 'nvidia-drm.modeset=1' to the kernel options
+		        # The sed command is used to append 'nvidia-drm.modeset=1' right after "rw" but before any other options that may be present.
+		        sudo sed -i 's/\(" rw\)\(.*"\)/\1 nvidia-drm.modeset=1\2/' "$CONF_FILE"
+
+		        if [ $? -eq 0 ]; then
+		            echo "Successfully added 'nvidia-drm.modeset=1' to the kernel options in $CONF_FILE."
+		        else
+		            echo "Failed to add 'nvidia-drm.modeset=1' to $CONF_FILE."
+		        fi
 		    fi
+		else
+		    echo "$CONF_FILE does not exist."
 		fi
+
 
 
 
